"""
State Graph Definition: Defines the data structure for the pipeline.
Every agent reads from this state and writes back to it.
"""

from typing import TypedDict, List, Dict, Optional, Annotated
import operator
from datetime import datetime
from typing import Dict


class FakeNewsState(TypedDict):
    """
    State schema for the fake news detection pipeline.
    
    This TypedDict defines all data that flows through the workflow.
    Each agent reads from this state and updates it.
    """
    
    # ========== INPUT SECTION ==========
    # Initial user input
    url: Optional[str]
    text: Optional[str]
    title: Optional[str]
    
    # ========== ARTICLE SECTION ==========
    # Output from Ingest Agent
    article: Optional[Dict]
    
    # ========== CLAIMS SECTION ==========
    # Output from Claim Detection Agent
    # Using Annotated with operator.add for accumulation
    claims: List[Dict]
    
    # ========== EMBEDDINGS SECTION ==========
    # Embeddings generated by Claim Embedding Agent
    embeddings_complete: bool
    
    # ========== EVIDENCE SECTION ==========
    # Output from Evidence Retrieval Agent
    evidence_count: int
    
    # ========== STANCE CLASSIFICATION SECTION ==========
    # Output from LLM Stance Classifier Agent
    classifications_complete: bool
    
    # ========== AGGREGATION SECTION ==========
    # Output from Aggregation Agent
    verdict: Optional[Dict]
    
    # ========== EXPLAINABILITY SECTION ==========
    # Output from Explainability Agent
    explanations: Optional[Dict]
    
    # ========== ERROR HANDLING ==========
    error: Optional[str]
    current_step: str
    
    # ========== METADATA ==========
    started_at: str
    completed_at: Optional[str]
    
    
    # ========== HELPER METHODS ==========
    @classmethod
    def create_initial(cls, url: Optional[str] = None, 
                      text: Optional[str] = None,
                      title: Optional[str] = None) -> Dict:
        """Create initial state for a new analysis."""
        return {
            # Input
            "url": url,
            "text": text,
            "title": title,
            
            # Processing
            "article": None,
            "claims": [],
            "embeddings_complete": False,
            "evidence_count": 0,
            "classifications_complete": False,
            
            # Output
            "verdict": None,
            "explanations": None,
            
            # Metadata
            "error": None,
            "current_step": "start",
            "started_at": datetime.now().isoformat(),
            "completed_at": None,
        }


# Type aliases for cleaner code
ClaimsList = Annotated[List[Dict], operator.add]
